### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by GivaldoOliveira** [jonatansalemes/nginx-admin#57]
{
  "errors": [
    {
      "status": 429,
      "message": "You have reached your monthly quota for Data Transfer. To continue and start enjoying unlimited transfer, upgrade your subscription"
    }
  ]
}

**Comment by ChrisFoliaTeam** [comment]
hi, i have a same probleme :( .

**Comment by seanpdiaz** [comment]
@jslsolucoes any chance we can get this issue resolved and moved to a more stable host?

**Comment by jslsolucoes** [comment]
Any suggestions ? Free hosts often do bandwith limits thats causing error above.

**Comment by zhushiyang** [comment]
I also encountered the same error. You can put the compiled package into GitHub so that we can download it normally

**Comment by jslsolucoes** [comment]
Even github will complain about free quota storage after exceeding 100mb forcing purchase more storage space. im current looking for sponsors or donations to keep project up to date.

**Comment by zhushiyang** [comment]
I have two suggestions that you can consider:
1. Use the free object storage function provided by the cloud service provider
2. The free cloud disk will also provide free download function

**Comment by zhushiyang** [comment]
> Even github will complain about free quota storage after exceeding 100mb forcing purchase more storage space. im current looking for sponsors or donations to keep project up to date.

I have two suggestions that you can consider:
1. Use the free object storage function provided by the cloud service provider
2. The free cloud disk will also provide free download function

**Comment by jslsolucoes** [comment]
> > Even github will complain about free quota storage after exceeding 100mb forcing purchase more storage space. im current looking for sponsors or donations to keep project up to date.
> 
> I have two suggestions that you can consider:
> 
> 1. Use the free object storage function provided by the cloud service provider
> 2. The free cloud disk will also provide free download function

which free object storage ?
